//
// Created by Giacomo Errani on 12/10/23.
//

#ifndef ROOT_TEMPLATE_PROJECT_APPLICATION_HPP
#define ROOT_TEMPLATE_PROJECT_APPLICATION_HPP

namespace Application{

}

#endif //ROOT_TEMPLATE_PROJECT_APPLICATION_HPP
