//
// Created by Giacomo Errani on 05/11/23.
//

#ifndef ROOT_TEMPLATE_PROJECT_PARTICLESTORAGESTRUCTURES_HPP
#define ROOT_TEMPLATE_PROJECT_PARTICLESTORAGESTRUCTURES_HPP

#include "Definitions.hpp"

namespace BASE_NS{

}

#endif //ROOT_TEMPLATE_PROJECT_PARTICLESTORAGESTRUCTURES_HPP
