//
// Created by Giacomo Errani on 02/11/23.
//

#ifndef ROOT_TEMPLATE_PROJECT_PARTICLEAANALYSER_HPP
#define ROOT_TEMPLATE_PROJECT_PARTICLEAANALYSER_HPP

#include "Definitions.hpp"

namespace BASE_NS{

}

#endif //ROOT_TEMPLATE_PROJECT_PARTICLEAANALYSER_HPP
